
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile.prod
    image: publishers-smb-backend/php
    container_name: publishers-smb-backend-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: publishers-smb-backend-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - /etc/letsencrypt/live/smb-api.alright.network/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/smb-api.alright.network/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
